import type { Metadata } from "next";
import { Cormorant, Jost } from "next/font/google";
import "./globals.css";
import ScrollToTop from "./(home)/components/ScrollToTop";

const cormorantGaramond = Cormorant({
  variable: "--font-cormorant-garamond",
  subsets: ["latin"],
  weight: "300"
});

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scrollbar-hidden">
      <body        className={`${cormorantGaramond.variable} ${jost.variable} antialiased scrollbar-hidden relative`}
      >
        {children}
        <ScrollToTop />
      </body>
    </html>
  );
}
